---
name: Tests

on:
  push:

jobs:
  NetBSD-On-Linux:
    name: ${{ matrix.box }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        box:
          - generic/netbsd9
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set `CPUS`
        run: |
          echo "CPUS=$(nproc)" >> ${GITHUB_ENV}

      - name: Provision VM
        uses: ./
        with:
          box: ${{ matrix.box }}
          cpus: ${{ env.CPUS }}

      - name: Run Test (uname) (VM)
        run: |
          if [ "$(uname -s)" = "NetBSD" ]; then
            echo "NetBSD detected."
          else
            echo "NetBSD not detected."
            exit 1
          fi
        shell: bash --noprofile --norc -euo pipefail {0}

      - name: Run Test (uname) (Host)
        run: |
          if [ "$(uname -s)" = "Linux" ]; then
            echo "Linux detected."
          else
            echo "Linux not detected."
            exit 1
          fi
        shell: /bin/bash --noprofile --norc -euo pipefail {0}

      - name: Prepare Test (working-directory) (VM)
        run: |
          mkdir new_working_directory
        shell: bash --noprofile --norc -euo pipefail {0}

      - name: Run Test (working-directory) (VM)
        run: |
          if [ "$(basename ${PWD})" = "new_working_directory" ]; then
            echo "Expected working directory detected."
          else
            echo "Expected working directory not detected."
            exit 1
          fi
        shell: bash --noprofile --norc -euo pipefail {0}
        working-directory: new_working_directory

  NetBSD-On-macOS:
    name: ${{ matrix.box }}
    runs-on: macos-13
    strategy:
      matrix:
        box:
          - generic/netbsd9
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set `CPUS`
        run: |
          echo "CPUS=$(getconf _NPROCESSORS_ONLN)" >> ${GITHUB_ENV}

      - name: Provision VM
        uses: ./
        with:
          box: ${{ matrix.box }}
          cpus: ${{ env.CPUS }}

      - name: Run Test (uname) (VM)
        run: |
          if [ "$(uname -s)" = "NetBSD" ]; then
            echo "NetBSD detected."
          else
            echo "NetBSD not detected."
            exit 1
          fi
        shell: bash --noprofile --norc -euo pipefail {0}

      - name: Run Test (uname) (Host)
        run: |
          if [ "$(uname -s)" = "Darwin" ]; then
            echo "Darwin detected."
          else
            echo "Darwin not detected."
            exit 1
          fi
        shell: /bin/bash --noprofile --norc -euo pipefail {0}

      - name: Prepare Test (working-directory) (VM)
        run: |
          mkdir new_working_directory
        shell: bash --noprofile --norc -euo pipefail {0}

      - name: Run Test (working-directory) (VM)
        run: |
          if [ "$(basename ${PWD})" = "new_working_directory" ]; then
            echo "Expected working directory detected."
          else
            echo "Expected working directory not detected."
            exit 1
          fi
        shell: bash --noprofile --norc -euo pipefail {0}
        working-directory: new_working_directory
